	AREA SORT_ASCENDING_ORDER, CODE, READONLY
ENTRY
	MOV R1, #5 ;LENGTH OF ARRAY
OUTLOOP
	MOV R3, R1
	LDR R0, =0X40000000
INLOOP
	LDR R2, [R0], #4
	LDR R4, [R0]
	CMP R4, R2
	BCS SKIP  ;IGNORE IF CARRY IS SET OR GREATER THAN CONDN OCCURES
	STR R2, [R0], #-4  ;SWAP IF SMALLER
	STR R4, [R0], #4
SKIP
	SUBS R3, R3, #1
	BNE INLOOP
	SUBS R1, R1, #1
	BNE OUTLOOP
STOP B STOP
	END